/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/acciones/acciones': RouteRecordInfo<'/acciones/acciones', '/acciones/acciones', Record<never, never>, Record<never, never>>,
    '/actas/crear/crearacta': RouteRecordInfo<'/actas/crear/crearacta', '/actas/crear/crearacta', Record<never, never>, Record<never, never>>,
    '/actas/crear/crearactaextend': RouteRecordInfo<'/actas/crear/crearactaextend', '/actas/crear/crearactaextend', Record<never, never>, Record<never, never>>,
    '/actas/crear/QR': RouteRecordInfo<'/actas/crear/QR', '/actas/crear/QR', Record<never, never>, Record<never, never>>,
    '/actas/editar/editarInfo': RouteRecordInfo<'/actas/editar/editarInfo', '/actas/editar/editarInfo', Record<never, never>, Record<never, never>>,
    '/actas/listar/lista': RouteRecordInfo<'/actas/listar/lista', '/actas/listar/lista', Record<never, never>, Record<never, never>>,
    '/actas/response/response': RouteRecordInfo<'/actas/response/response', '/actas/response/response', Record<never, never>, Record<never, never>>,
    '/actas/response/userexistent': RouteRecordInfo<'/actas/response/userexistent', '/actas/response/userexistent', Record<never, never>, Record<never, never>>,
    '/actas/response/userInexist': RouteRecordInfo<'/actas/response/userInexist', '/actas/response/userInexist', Record<never, never>, Record<never, never>>,
    '/asistentes/asistentes': RouteRecordInfo<'/asistentes/asistentes', '/asistentes/asistentes', Record<never, never>, Record<never, never>>,
    '/asistentes/create': RouteRecordInfo<'/asistentes/create', '/asistentes/create', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/error/error': RouteRecordInfo<'/error/error', '/error/error', Record<never, never>, Record<never, never>>,
    '/gracias/firmada': RouteRecordInfo<'/gracias/firmada', '/gracias/firmada', Record<never, never>, Record<never, never>>,
  }
}
